herbs_and_amber/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('supplies/', views.supplies, name='supplies'),
    path('methods/', views.methods, name='methods'),
    path('tinctures/', views.tinctures_index, name='index'),
    path('tinctures/<int:tincture_id>/', views.tinctures_detail, name='detail'),
    path('herbs/', views.herbs_index, name='herbs_index'),
    path('herbs/<int:herb_id>/', views.herbs_detail, name='herbs_detail'),
    path('tinctures/create/', views.TinctureCreate.as_view(), name='tincture_create'),
    path('tinctures/<int:pk>/update/', views.TinctureUpdate.as_view(), name='tinctures_update'),
    path('tinctures/<int:pk>/delete/', views.TinctureDelete.as_view(), name='tinctures_delete'),
    path('herbs/create/', views.HerbCreate.as_view(), name='herb_create'),
    path('herbs/<int:pk>/update/', views.HerbUpdate.as_view(), name='herbs_update'),
    path('herbs/<int:pk>/delete/', views.HerbDelete.as_view(), name='herbs_delete'),
    path('tinctures/<int:tincture_id>/add_batch/', views.add_batch, name='add_batch'),
]

main_app/models.py
from django.db import models
from datetime import date

# Create your models here.

MATERIALS = (
    ('L', 'Leaf'),
    ('F', 'Flower'),
    ('R', 'Root'),
    ('B', 'Bark'),
    ('E', 'Berry'),
)

STATES = (
    ('F', 'Fresh'),
    ('D', 'Dried')
)

class Herb(models.Model):
    
    name = models.CharField(max_length=100)
    material = models.CharField(
        max_length=1,
        choices=MATERIALS,
        default=MATERIALS[0][0]
    )
    state = models.CharField(
        max_length=1,
        choices=STATES,
        default=STATES[0][0]
    )
    properties = models.TextField(max_length=500)
    image = models.CharField(max_length=100, default='https://i.postimg.cc/0NQ0ty2L/65411-E92-1783-46-D3-907-F-7-FA037834-E9-E.jpg')
        
    def __str__(self):
        return self.name

class Tincture(models.Model):
    name = models.CharField(max_length=100)
    solvent = models.CharField(max_length=100)
    herbs = models.ManyToManyField(Herb)
    image = models.CharField(max_length=100, default='https://i.postimg.cc/T3hVGrk7/Default.jpg')
        
    def __str__(self):
        return self.name
    
class Batch(models.Model):
    prep_date = models.DateField('prep date')
    ready_date = models.DateField('ready date')
    tincture = models.ForeignKey(Tincture, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"New Batch prepped on {self.prep_date}. To be strained and bottled on {self.ready_date}"
    
    class Meta:
        ordering = ['-prep_date']

main_app/forms.py
from django.forms import ModelForm
from .models import Batch

class BatchForm(ModelForm):
  class Meta:
    model = Batch
    fields = ['prep_date', 'ready_date']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Herb, Tincture
from .forms import BatchForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def supplies(request):
    return render(request, 'supplies.html')

def methods(request):
    return render(request, 'methods.html')

def herbs_index(request):
    herbs = Herb.objects.all()
    return render(request, 'herbs/index.html', { 'herbs': herbs })

def herbs_detail(request, herb_id):
    herb = Herb.objects.get(id=herb_id)
    return render(request, 'herbs/detail.html', { 'herb': herb })

class HerbCreate(CreateView):
    model = Herb
    fields = '__all__'
    success_url = '/herbs/'
    
class HerbUpdate(UpdateView):
    model = Herb
    fields = ['material', 'state', 'properties', 'image']
    success_url = '/herbs/'
    
class HerbDelete(DeleteView):
    model = Herb
    success_url = '/herbs/'

def tinctures_index(request):
    tinctures = Tincture.objects.all()
    return render(request, 'tinctures/index.html', { 'tinctures': tinctures })

def tinctures_detail(request, tincture_id):
    tincture = Tincture.objects.get(id=tincture_id)
    batch_form = BatchForm()
    return render(request, 'tinctures/detail.html', {
        'tincture': tincture, 'batch_form': batch_form
    })

class TinctureCreate(CreateView):
    model = Tincture
    fields = '__all__'
    success_url = '/tinctures/'
    
class TinctureUpdate(UpdateView):
    model = Tincture
    fields = ['herbs', 'solvent', 'image']
    success_url = '/tinctures/'
    
class TinctureDelete(DeleteView):
    model = Tincture
    success_url = '/tinctures/'
    
def add_batch(request, tincture_id):
    form = BatchForm(request.POST)
    if form.is_valid():
        new_batch = form.save(commit=False)
        new_batch.tincture_id = tincture_id
        new_batch.save()
    return redirect('detail', tincture_id=tincture_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

    <h3>About Herbs & Amber</h3>
    <style>
        #bio {
            padding-top: 10px;
        }
    </style>
    <hr />
    <div class="row">
    <p class="col s6">
        <span class="flow-text">
        Welcome to Herbs & Amber, a haven for those who want to explore the ancient art of tincture-making in the context of modern holistic wellness. Our website is a sanctuary for those seeking to nurture their mind, body, and spirit through the natural healing power of herbs. Discover how to craft botanical treasures to fill your amber vessels and relish the sense of calm and balance you find on your tincture-making journey.
        </span>
    </p>
    <img class="col s6" id="bio" src="https://i.postimg.cc/8kMrSTh6/2777-E9-D0-115-E-472-A-B20-F-40-A7-D3-B7-FDB7.jpg" alt="Herbologist" />
    </div>
    <blockquote style="border-left: 5px solid #d1c4e9">
        <strong>DISCLAIMER:</strong> The content provided on Herbs & Amber is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. While we strive to offer accurate and up-to-date information, we recommend consulting with a qualified healthcare professional before using any herbal remedies or tinctures. Take care to research and understand the properties of each herb before use, and remember that individual experiences may vary.
        </blockquote>
    <hr />
    <p>
        “The Earth is what we all have in common.”
        <br/>
        — Wendell Berry
    </p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Herbs & Amber</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
      });
    </script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper #d1c4e9 deep-purple lighten-3">
          <ul>
            <li class="home">
              <style>
                .home a:hover {
                  background-color: rgba(0, 0, 0, 0) !important;
                }
              </style>
              <a href="/">
                <style>
                  .logo {
                    margin-top: 10px;
                    margin-left: 10px;
                    height: 45px;
                  }
                </style>
                <img class="logo" src="https://i.postimg.cc/WbZm5Kdv/image.png" alt="green ampersand">
              </a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'supplies' %}">Supplies</a></li>
            <li><a href="{% url 'methods' %}">Methods</a></li>
            <li><a href="{% url 'herbs_index' %}">Herbs</a></li>
            <li><a href="{% url 'index' %}">Tinctures</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer #d1c4e9 deep-purple lighten-3">
      <div class="center">
        All Rights Reserved, &copy; 2024 Herbs & Amber &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/herbs/detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ herb.name }}</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ herb.get_state_display }} {{ herb.name }}</span>
    <p><strong>Type of Herbal Material:</strong> {{ herb.get_material_display }}</p>
    <p><strong>Properties:</strong> {{ herb.properties }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'herbs_update' herb.id %}">Edit</a>
    <a href="{% url 'herbs_delete' herb.id %}">Delete</a>
  </div>
</div> 

{% endblock %}

main_app/templates/herbs/index.html
{% extends 'base.html' %} {% block content %}

<style>
    
.card {
    float: left;
    display: inline-block;
    margin: 20px;
}

@media only screen
and (max-width : 1600px) {
.card { width: 250px;}
}

</style>

<h3>Herbal Ingredients</h3>

{% for herb in herbs %}

<div class="card hoverable">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="{{ herb.image }}"/>
    </div>
    <div class="card-content activator grey-text text-darken-4">
        <span class="card-title">
            <a href="{% url 'herbs_detail' herb.id %}">{{ herb.get_state_display }} {{ herb.name }}</a>
            <i class="material-icons right">more_vert</i>
        </span>
    </div>
    <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">
            <span class="card-title">{{ herb.name }}</span>
            <i class="material-icons right">close</i>
        </span>
        <div class="card-content">
            <p><strong>Type:</strong> {{ herb.get_material_display }}</p>
            <p><strong>State:</strong> {{ herb.get_state_display }}</p>
          </div>
    </div>
</div>

{% endfor %}

<div class="card hoverable">
    <a href="{% url 'herb_create' %}">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="https://i.postimg.cc/0NQ0ty2L/65411-E92-1783-46-D3-907-F-7-FA037834-E9-E.jpg" alt="Herb Assortment"/>
    </div>
        <div class="card-content">
            <span class="card-title">
                ADD HERB
            </span>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/home.html
<style>

  body {
    background-image: url('https://i.postimg.cc/250nqNK4/1.png');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  
  button {
    border-color: #a0b666;
    background-color: #f6f1e1;
    display: block;
    margin: auto;
    padding-top: 10px;
    padding-bottom: 10px;
    padding-left: 50px;
    padding-right: 50px;
    border-radius: 10px;
  }

  a {
    text-decoration: none;
    font-size: xx-large;
    color: #a0b666;
  }

  img {
    display: block;
    margin: auto;
  }

</style>

<div>
  <button>
    <a href="{% url 'about' %}"><strong>ENTER</strong></a>
  </button>
</div>
<img src="https://i.postimg.cc/fLkmmqG1/2.png" alt="Herb Cupboard"/>

main_app/templates/main_app/herb_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Herb</h1>

<h4>
  Are you sure you want to delete <span class="purple-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'herbs_detail' herb.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/herb_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}

<h1>Edit <span class="purple-text">{{ object.name }}</span></h1>

{% else %}

<h1>Add Herb</h1>

{% endif %}

<form action="" method="POST">

  {% csrf_token %}

  <table>
    {{ form.as_table }}
  </table></br>

  <button class="btn waves-effect waves-light" type="submit" name="action">
    Submit <i class="material-icons right">send</i>
  </button>

</form>

{% endblock %}

main_app/templates/main_app/tincture_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Tincture</h1>

<h4>
  Are you sure you want to delete <span class="purple-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' tincture.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/tincture_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}

<h1>Edit <span class="purple-text">{{ object.name }}</span></h1>

{% else %}

<h1>Add Tincture</h1>

{% endif %}

<form action="" method="POST">

  {% csrf_token %}

  <table>
    {{ form.as_table }}
  </table></br>

  <button class="btn waves-effect waves-light" type="submit" name="action">
    Submit <i class="material-icons right">send</i>
  </button>

</form>

{% endblock %}

main_app/templates/methods.html
{% extends 'base.html' %} {% block content %}

<h3>Methods</h3>
<hr />
<container class="row">
    <div class="col s4">
        <h4>Folk</h4>
            <ol>
                <li>Step One:</li>
            </ol>
    </div>
    <div class="col s4">
        <h4>Ratio</h4>
            <ol>
                <li>Step One:</li>
            </ol>
    </div>
    <div class="col s4">
        <h4>Percolation</h4>
            <ol>
                <li>Step One:</li>
            </ol>
    </div>
</container>
<hr />
<p>
    “You are not Atlas carrying the world on your shoulder. It is good to remember that the planet is carrying you.”
    <br/>
    — Vandana Shiva
</p>

{% endblock %}

main_app/templates/supplies.html
{% extends 'base.html' %} {% block content %}

<h3>Supplies</h3>
<hr />
    <container class="row">
        <div class="col s6">
            <h4>Required</h4>
                <ul>
                    <li>Spring Water</li>
                    <li>Sterilized Glass Canning Jars</li>
                    <li>Glass Bottles (Ideally Amber)</li>
                    <li>Bottle Labels</li>
                    <li>Fine Mesh Sieve</li>
                    <li>Cheesecloth</li>
                    <li></li>
                </ul>
        </div>
        <div class="col s6">
            <h4>Optional</h4>
                <ul>
                    <li>Blender</li>
                    <li>Crock Pot</li>
                    <li>Thermometer</li>
                    <li>Percolation Kit</li>
                </ul>
        </div>
    </container>
    <hr />
    <p>
        “Look deep into nature, and then you will understand everything better.”
        <br/>
        — Albert Einstein
    </p>

{% endblock %}

main_app/templates/tinctures/detail.html
{% extends 'base.html' %} {% block content %}

<style>

  img {
    display: block;
    margin: auto;
  }

</style>

<h2>{{ tincture.name }}</h2>

<div class="card col s3" class="valign-wrapper">
  <div class="card-content">
    <img class="responsive-img" src="{{ tincture.image }}" alt="{{ tincture.name }}">
    <p>Solvent: {{ tincture.solvent }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'tinctures_update' tincture.id %}">Edit</a>
    <a href="{% url 'tinctures_delete' tincture.id %}">Delete</a>
  </div> 
</div>

<div class="row">
  <div class="col s3">
    <h3>{{ tincture.name }} Herbs</h3>
    {% if tincture.herbs.count %} {% for herb in tincture.herbs.all %}
    <div class="card hoverable">
      <a href="{% url 'herbs_detail' herb.id %}">
      <div class="card-content">
        <span class="card-title">
          {{ herb.get_state_display }} {{ herb.name }}
        </span>
      </div>
      </a>
    </div>
    {% endfor %}
    {% endif %}
</div>

<br/>

<div>
<table class="striped">
  <thead>
    <tr>
      <th>Batches</th>
    </tr>
  </thead>
  <tbody>
    {% for batch in tincture.batch_set.all %}
      <tr>
        <td><strong>Prepped:</strong> {{ batch.prep_date }}</td>
        <td><strong>Ready:</strong> {{ batch.ready_date }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<form action="{% url 'add_batch' tincture.id %}" method="POST">
  {% csrf_token %} {{ batch_form.as_p }}
  <input type="submit" class="btn" value="Add Batch" />
</form>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>

{% endblock %}

main_app/templates/tinctures/index.html
{% extends 'base.html' %} {% block content %}

<style>

.card {
    float: left;
    display: inline-block;
    margin: 20px;
}

@media only screen
and (max-width : 1600px) {
.card { width: 250px;}
}
    
</style>

<div class="card-heading">
<h3>Tinctures</h3>
</div>

{% for tincture in tinctures %}

<div class="card hoverable">
    <a href="{% url 'detail' tincture.id %}">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="{{ tincture.image }}" alt="{{ tincture.name }}"/>
    </div>
        <div class="card-content">
            <span class="card-title">{{ tincture.name }}</span>
        </div>
</div>
</a>
</div>

{% endfor %}

<div class="card hoverable">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="https://i.postimg.cc/T3hVGrk7/Default.jpg" alt="Empty Tincture Bottle"/>
    </div>
    <a href="{% url 'tincture_create' %}">
        <div class="card-content">
            <span class="card-title">ADD TINCTURE</span>
        </div>
    </a>
</div>
</div>
</div>

{% endblock %}